### ISSUE TITLE
Decidir o nome da aplicação de Quiz

### ISSUE THREAD

**Issue by oxechicao** [FeliciLab/AvaliacaoDaForcaDeTrabalho#5]
- [ ] Avalia Força Saúde
- [ ] QualiQuiz
- [ ] QualificAção
- [ ] QualiFlix
- [ ] QualiFlex
- [ ] Avalíi
- [ ] Qualiz
- [x] Qualiz Saúde

**Comment by vicmagpac** [comment]
Nome concluído? Podemos finalizar a issue?
